name: Run Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Laravel 11 (light support)
          - php: 8.4
            laravel: "11.*"
            testbench: "9.*"
            pest: ^3.7.4
            pest-plugin: ^3.0
            dependency-version: prefer-stable

          # Laravel 12 (medium support)
          - php: 8.4
            laravel: "12.*"
            testbench: "10.*"
            pest: ^3.7.4
            pest-plugin: ^3.0
            dependency-version: prefer-stable

          # Laravel 13 (main support)
          - php: 8.3
            laravel: "13.*"
            testbench: "11.*"
            pest: ^4.0
            pest-plugin: ^4.0
            dependency-version: prefer-lowest

          - php: 8.4
            laravel: "13.*"
            testbench: "11.*"
            pest: ^4.0
            pest-plugin: ^4.0
            dependency-version: prefer-stable

          - php: 8.5
            laravel: "13.*"
            testbench: "11.*"
            pest: ^4.0
            pest-plugin: ^4.0
            dependency-version: prefer-stable

          - php: 8.5
            laravel: "13.*"
            testbench: "11.*"
            pest: ^4.0
            pest-plugin: ^4.0
            dependency-version: prefer-lowest

        exclude:
          - laravel: "13.*"
            php: 8.2

          - laravel: "11.*"
            php: 8.3

    name: PHP${{ matrix.php }} - Laravel${{ matrix.laravel }} - Testbench${{ matrix.testbench }} - Pest${{ matrix.pest }} - Pest-Plugin${{ matrix.pest-plugin }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, mbstring, zip, sqlite, bcmath, soap, intl
          coverage: none

      - name: Install dependencies
        run: |
          composer require --dev \
            "laravel/framework:${{ matrix.laravel }}" \
            "orchestra/testbench:${{ matrix.testbench }}" \
            "pestphp/pest:${{ matrix.pest }}" \
            "pestphp/pest-plugin-laravel:${{ matrix.pest-plugin }}" \
            --no-interaction --no-update

          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/pest --ci

  lint-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, dom, curl

      - run: composer install --no-interaction

      - run: vendor/bin/pint --test

  phpstan-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, dom, curl

      - run: composer install --no-interaction

      - run: vendor/bin/phpstan analyse